/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ControlButton: typeof import('./src/components/ControlButton.vue')['default']
    CrosshairsTool: typeof import('./src/components/tools/crosshairs/CrosshairsTool.vue')['default']
    CrosshairSVG2D: typeof import('./src/components/tools/crosshairs/CrosshairSVG2D.vue')['default']
    CrosshairsWidget2D: typeof import('./src/components/tools/crosshairs/CrosshairsWidget2D.vue')['default']
    GroupableItem: typeof import('./src/components/GroupableItem.vue')['default']
    HeaderModule: typeof import('./src/components/HeaderModule.vue')['default']
    IMdiCrosshairs: typeof import('~icons/mdi/crosshairs')['default']
    IMdiRuler: typeof import('~icons/mdi/ruler')['default']
    ItemGroup: typeof import('./src/components/ItemGroup.vue')['default']
    LayoutGrid: typeof import('./src/components/LayoutGrid.vue')['default']
    MeasurementsModule: typeof import('./src/components/MeasurementsModule.vue')['default']
    ModulePanel: typeof import('./src/components/ModulePanel.vue')['default']
    PaintTool: typeof import('./src/components/tools/paint/PaintTool.vue')['default']
    PaintWidget2D: typeof import('./src/components/tools/paint/PaintWidget2D.vue')['default']
    PolygonSVG2D: typeof import('./src/components/tools/polygon/PolygonSVG2D.vue')['default']
    PolygonTool: typeof import('./src/components/tools/polygon/PolygonTool.vue')['default']
    PolygonWidget2D: typeof import('./src/components/tools/polygon/PolygonWidget2D.vue')['default']
    QuickInfo: typeof import('./src/components/QuickInfo.vue')['default']
    ResetViews: typeof import('./src/components/tools/ResetViews.vue')['default']
    RulerSVG2D: typeof import('./src/components/tools/ruler/RulerSVG2D.vue')['default']
    RulerTool: typeof import('./src/components/tools/ruler/RulerTool.vue')['default']
    RulerWidget2D: typeof import('./src/components/tools/ruler/RulerWidget2D.vue')['default']
    SegmentsModule: typeof import('./src/components/SegmentsModule.vue')['default']
    SelectTool: typeof import('./src/components/tools/SelectTool.vue')['default']
    SliceSlider: typeof import('./src/components/SliceSlider.vue')['default']
    SliceViewer: typeof import('./src/components/SliceViewer.vue')['default']
    SliceViewerOverlay: typeof import('./src/components/SliceViewerOverlay.vue')['default']
    ToolModule: typeof import('./src/components/ToolModule.vue')['default']
    ViewOverlayGrid: typeof import('./src/components/ViewOverlayGrid.vue')['default']
    VtkBaseSliceRepresentation: typeof import('./src/components/vtk/VtkBaseSliceRepresentation.vue')['default']
    VtkMouseInteractionManipulator: typeof import('./src/components/vtk/VtkMouseInteractionManipulator.vue')['default']
    VtkSegmentationSliceRepresentation: typeof import('./src/components/vtk/VtkSegmentationSliceRepresentation.vue')['default']
    VtkSliceView: typeof import('./src/components/vtk/VtkSliceView.vue')['default']
    VtkSliceViewSlicingManipulator: typeof import('./src/components/vtk/VtkSliceViewSlicingManipulator.vue')['default']
    VtkSliceViewWindowManipulator: typeof import('./src/components/vtk/VtkSliceViewWindowManipulator.vue')['default']
  }
}
